name: build release from tag
on:
  create:
    tags:
      - '*'
  push:


jobs:
  Build-Version:
    runs-on: ubuntu-latest
    # env:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - run: chmod +x ./.github/workflows/scripts/generate-version.sh && ./.github/workflows/scripts/generate-version.sh
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: |
            /home/runner/work/pipeline/*
            !/home/runner/work/pipeline/.git/*